Repository mautic/hacktoberfest-no-code, pull requests merged in 2024-10, with the labels that each got.

#16 Update: 2024.md
  2024.md
Labels: hacktoberfest-accepted

#17 Update 2024.md
  2024.md
Labels: hacktoberfest-accepted

#19 Update 2024.md
  2024.md
Labels: hacktoberfest-accepted

#26 Tested PR: Error: File is too large
  2024.md
Labels: hacktoberfest-accepted

#30 Update 2024.md
  2024.md
Labels: hacktoberfest-accepted

#36 #13767: Code review
  2024.md
Labels: hacktoberfest, hacktoberfest-accepted

#39 Created Dropsolid visuals for Mautic Conference Europe
  2024.md
Labels: hacktoberfest, hacktoberfest-accepted

#38 Update 2024.md
  2024.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 Update 2024.md
  2024.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 Update 2024.md
  2024.md
Labels: hacktoberfest-accepted

#53 Reviewed #14201
  2024.md
Labels: hacktoberfest, hacktoberfest-accepted

#56 Update 2024.md
  2024.md
Labels: hacktoberfest-accepted

#61 Update 2024.md
  2024.md
Labels: hacktoberfest-accepted

#72 Created layouts for transactional emails for MautiCon Lisbon
  2024.md
Labels: hacktoberfest-accepted, hacktober-2024

#76 Update 2024.md - Resolves issue #74
  2024.md
Labels: hacktoberfest-accepted, translations, hacktober-2024

#65 Update 2024.md with the link to the PR (#14201) I tested
  2024.md
Labels: hacktoberfest-accepted, hacktober-2024

#77 Designed Images for MautiCon Lisbon
  2024.md
Labels: hacktoberfest-accepted, hacktober-2024

#78 User testing and code review
  2024.md
Labels: hacktoberfest

#79 Update 2024.md - Added new entry for issue #75
  2024.md
Labels: hacktoberfest-accepted, translations, hacktober-2024

#81 feat: Add Ayu Adiati's contribution to 2024.md
  2024.md
Labels: content-writing-editing, no-code, marketing, hacktoberfest-accepted, hacktober-2024

#83 Membership Flyer Design For MautiCon Lisbon
  2024.md
Labels: no-code, design, hacktoberfest-accepted, hacktober-2024

#84 peer reviews and user testing
  2024.md
Labels: hacktoberfest
